### ISSUE TITLE
Does not work on Mac (Xcode 7.2)

### ISSUE THREAD

**Issue by zippy1978** [aciidb0mb3r/atom-swift-debugger#2]
After setting e and p, I get _<unknown>:0: error: no such file or directory: 'build'_ when I try to run.

For info p=/Library/Developer/CommandLineTools/usr/bin (using Xcode 7.2).

**Comment by kenwilcox** [comment]
I tried it with Xcode 7.2 and got the same error (I believe it's swift 2.1) - I downloaded and installed Swift 2.2 from swift.org [https://swift.org/download/#latest-development-snapshots](https://swift.org/download/#latest-development-snapshots) and it worked.

I used e=MySwiftProject p=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin

**Comment by aciidgh** [comment]
Hi
It cannot work with swift bundled with Xcode ie
swift 2.1 because it doesn't contained the Swift Package Manager which is used to build the files. 
get the latest snapshot from swift.org and it should work as expected.
